const themes = {'default': 'Default','amber_blue': 'Amber Blue', 
'amber_cyan': 'Amber Cyan', 
'amber_deep_orange': 'Amber Deep Orange', 
'amber_deep_purple': 'Amber Deep Purple', 
'amber_green': 'Amber Green', 
'amber_indigo': 'Amber Indigo', 
'amber_light_blue': 'Amber Light Blue', 
'amber_light_green': 'Amber Light Green', 
'amber_lime': 'Amber Lime', 
'amber_orange': 'Amber Orange', 
'amber_pink': 'Amber Pink', 
'amber_purple': 'Amber Purple', 
'amber_red': 'Amber Red', 
'amber_teal': 'Amber Teal', 
'amber_yellow': 'Amber Yellow', 
'blue_grey_amber': 'Blue Grey Amber', 
'blue_grey_blue': 'Blue Grey Blue', 
'blue_grey_cyan': 'Blue Grey Cyan', 
'blue_grey_deep_orange': 'Blue Grey Deep Orange', 
'blue_grey_deep_purple': 'Blue Grey Deep Purple', 
'blue_grey_green': 'Blue Grey Green', 
'blue_grey_indigo': 'Blue Grey Indigo', 
'blue_grey_light_blue': 'Blue Grey Light Blue', 
'blue_grey_light_green': 'Blue Grey Light Green', 
'blue_grey_lime': 'Blue Grey Lime', 
'blue_grey_orange': 'Blue Grey Orange', 
'blue_grey_pink': 'Blue Grey Pink', 
'blue_grey_purple': 'Blue Grey Purple', 
'blue_grey_red': 'Blue Grey Red', 
'blue_grey_teal': 'Blue Grey Teal', 
'blue_grey_yellow': 'Blue Grey Yellow', 
'blue_amber': 'Blue Amber', 
'blue_cyan': 'Blue Cyan', 
'blue_deep_orange': 'Blue Deep Orange', 
'blue_deep_purple': 'Blue Deep Purple', 
'blue_green': 'Blue Green', 
'blue_indigo': 'Blue Indigo', 
'blue_light_blue': 'Blue Light Blue', 
'blue_light_green': 'Blue Light Green', 
'blue_lime': 'Blue Lime', 
'blue_orange': 'Blue Orange', 
'blue_pink': 'Blue Pink', 
'blue_purple': 'Blue Purple', 
'blue_red': 'Blue Red', 
'blue_teal': 'Blue Teal', 
'blue_yellow': 'Blue Yellow', 
'brown_amber': 'Brown Amber', 
'brown_blue': 'Brown Blue', 
'brown_cyan': 'Brown Cyan', 
'brown_deep_orange': 'Brown Deep Orange', 
'brown_deep_purple': 'Brown Deep Purple', 
'brown_green': 'Brown Green', 
'brown_indigo': 'Brown Indigo', 
'brown_light_blue': 'Brown Light Blue', 
'brown_light_green': 'Brown Light Green', 
'brown_lime': 'Brown Lime', 
'brown_orange': 'Brown Orange', 
'brown_pink': 'Brown Pink', 
'brown_purple': 'Brown Purple', 
'brown_red': 'Brown Red', 
'brown_teal': 'Brown Teal', 
'brown_yellow': 'Brown Yellow', 
'cyan_amber': 'Cyan Amber', 
'cyan_blue': 'Cyan Blue', 
'cyan_deep_orange': 'Cyan Deep Orange', 
'cyan_deep_purple': 'Cyan Deep Purple', 
'cyan_green': 'Cyan Green', 
'cyan_indigo': 'Cyan Indigo', 
'cyan_light_blue': 'Cyan Light Blue', 
'cyan_light_green': 'Cyan Light Green', 
'cyan_lime': 'Cyan Lime', 
'cyan_orange': 'Cyan Orange', 
'cyan_pink': 'Cyan Pink', 
'cyan_purple': 'Cyan Purple', 
'cyan_red': 'Cyan Red', 
'cyan_teal': 'Cyan Teal', 
'cyan_yellow': 'Cyan Yellow', 
'dark_mode': 'Dark Mode', 
'deep_orange_amber': 'Deep Orange Amber', 
'deep_orange_blue': 'Deep Orange Blue', 
'deep_orange_cyan': 'Deep Orange Cyan', 
'deep_orange_deep_purple': 'Deep Orange Deep Purple', 
'deep_orange_green': 'Deep Orange Green', 
'deep_orange_indigo': 'Deep Orange Indigo', 
'deep_orange_light_blue': 'Deep Orange Light Blue', 
'deep_orange_light_green': 'Deep Orange Light Green', 
'deep_orange_lime': 'Deep Orange Lime', 
'deep_orange_orange': 'Deep Orange Orange', 
'deep_orange_pink': 'Deep Orange Pink', 
'deep_orange_purple': 'Deep Orange Purple', 
'deep_orange_red': 'Deep Orange Red', 
'deep_orange_teal': 'Deep Orange Teal', 
'deep_orange_yellow': 'Deep Orange Yellow', 
'deep_purple_amber': 'Deep Purple Amber', 
'deep_purple_blue': 'Deep Purple Blue', 
'deep_purple_cyan': 'Deep Purple Cyan', 
'deep_purple_deep_orange': 'Deep Purple Deep Orange', 
'deep_purple_green': 'Deep Purple Green', 
'deep_purple_indigo': 'Deep Purple Indigo', 
'deep_purple_light_blue': 'Deep Purple Light Blue', 
'deep_purple_light_green': 'Deep Purple Light Green', 
'deep_purple_lime': 'Deep Purple Lime', 
'deep_purple_orange': 'Deep Purple Orange', 
'deep_purple_pink': 'Deep Purple Pink', 
'deep_purple_purple': 'Deep Purple Purple', 
'deep_purple_red': 'Deep Purple Red', 
'deep_purple_teal': 'Deep Purple Teal', 
'deep_purple_yellow': 'Deep Purple Yellow', 
'default': 'Default', 
'green_amber': 'Green Amber', 
'green_blue': 'Green Blue', 
'green_cyan': 'Green Cyan', 
'green_deep_orange': 'Green Deep Orange', 
'green_deep_purple': 'Green Deep Purple', 
'green_indigo': 'Green Indigo', 
'green_light_blue': 'Green Light Blue', 
'green_light_green': 'Green Light Green', 
'green_lime': 'Green Lime', 
'green_orange': 'Green Orange', 
'green_pink': 'Green Pink', 
'green_purple': 'Green Purple', 
'green_red': 'Green Red', 
'green_teal': 'Green Teal', 
'green_yellow': 'Green Yellow', 
'grey_amber': 'Grey Amber', 
'grey_blue': 'Grey Blue', 
'grey_cyan': 'Grey Cyan', 
'grey_deep_orange': 'Grey Deep Orange', 
'grey_deep_purple': 'Grey Deep Purple', 
'grey_green': 'Grey Green', 
'grey_indigo': 'Grey Indigo', 
'grey_light_blue': 'Grey Light Blue', 
'grey_light_green': 'Grey Light Green', 
'grey_lime': 'Grey Lime', 
'grey_orange': 'Grey Orange', 
'grey_pink': 'Grey Pink', 
'grey_purple': 'Grey Purple', 
'grey_red': 'Grey Red', 
'grey_teal': 'Grey Teal', 
'grey_yellow': 'Grey Yellow', 
'indigo_amber': 'Indigo Amber', 
'indigo_blue': 'Indigo Blue', 
'indigo_cyan': 'Indigo Cyan', 
'indigo_deep_orange': 'Indigo Deep Orange', 
'indigo_deep_purple': 'Indigo Deep Purple', 
'indigo_green': 'Indigo Green', 
'indigo_light_blue': 'Indigo Light Blue', 
'indigo_light_green': 'Indigo Light Green', 
'indigo_lime': 'Indigo Lime', 
'indigo_orange': 'Indigo Orange', 
'indigo_pink': 'Indigo Pink', 
'indigo_purple': 'Indigo Purple', 
'indigo_red': 'Indigo Red', 
'indigo_teal': 'Indigo Teal', 
'indigo_yellow': 'Indigo Yellow', 
'light_blue_amber': 'Light Blue Amber', 
'light_blue_blue': 'Light Blue Blue', 
'light_blue_cyan': 'Light Blue Cyan', 
'light_blue_deep_orange': 'Light Blue Deep Orange', 
'light_blue_deep_purple': 'Light Blue Deep Purple', 
'light_blue_green': 'Light Blue Green', 
'light_blue_indigo': 'Light Blue Indigo', 
'light_blue_light_green': 'Light Blue Light Green', 
'light_blue_lime': 'Light Blue Lime', 
'light_blue_orange': 'Light Blue Orange', 
'light_blue_pink': 'Light Blue Pink', 
'light_blue_purple': 'Light Blue Purple', 
'light_blue_red': 'Light Blue Red', 
'light_blue_teal': 'Light Blue Teal', 
'light_blue_yellow': 'Light Blue Yellow', 
'light_green_amber': 'Light Green Amber', 
'light_green_blue': 'Light Green Blue', 
'light_green_cyan': 'Light Green Cyan', 
'light_green_deep_orange': 'Light Green Deep Orange', 
'light_green_deep_purple': 'Light Green Deep Purple', 
'light_green_green': 'Light Green Green', 
'light_green_indigo': 'Light Green Indigo', 
'light_green_light_blue': 'Light Green Light Blue', 
'light_green_lime': 'Light Green Lime', 
'light_green_orange': 'Light Green Orange', 
'light_green_pink': 'Light Green Pink', 
'light_green_purple': 'Light Green Purple', 
'light_green_red': 'Light Green Red', 
'light_green_teal': 'Light Green Teal', 
'light_green_yellow': 'Light Green Yellow', 
'lime_amber': 'Lime Amber', 
'lime_blue': 'Lime Blue', 
'lime_cyan': 'Lime Cyan', 
'lime_deep_orange': 'Lime Deep Orange', 
'lime_deep_purple': 'Lime Deep Purple', 
'lime_green': 'Lime Green', 
'lime_indigo': 'Lime Indigo', 
'lime_light_blue': 'Lime Light Blue', 
'lime_light_green': 'Lime Light Green', 
'lime_orange': 'Lime Orange', 
'lime_pink': 'Lime Pink', 
'lime_purple': 'Lime Purple', 
'lime_red': 'Lime Red', 
'lime_teal': 'Lime Teal', 
'lime_yellow': 'Lime Yellow', 
'orange_amber': 'Orange Amber', 
'orange_blue': 'Orange Blue', 
'orange_cyan': 'Orange Cyan', 
'orange_deep_orange': 'Orange Deep Orange', 
'orange_deep_purple': 'Orange Deep Purple', 
'orange_green': 'Orange Green', 
'orange_indigo': 'Orange Indigo', 
'orange_light_blue': 'Orange Light Blue', 
'orange_light_green': 'Orange Light Green', 
'orange_lime': 'Orange Lime', 
'orange_pink': 'Orange Pink', 
'orange_purple': 'Orange Purple', 
'orange_red': 'Orange Red', 
'orange_teal': 'Orange Teal', 
'orange_yellow': 'Orange Yellow', 
'pink_amber': 'Pink Amber', 
'pink_blue': 'Pink Blue', 
'pink_cyan': 'Pink Cyan', 
'pink_deep_orange': 'Pink Deep Orange', 
'pink_deep_purple': 'Pink Deep Purple', 
'pink_green': 'Pink Green', 
'pink_indigo': 'Pink Indigo', 
'pink_light_blue': 'Pink Light Blue', 
'pink_light_green': 'Pink Light Green', 
'pink_lime': 'Pink Lime', 
'pink_orange': 'Pink Orange', 
'pink_purple': 'Pink Purple', 
'pink_red': 'Pink Red', 
'pink_teal': 'Pink Teal', 
'pink_yellow': 'Pink Yellow', 
'purple_amber': 'Purple Amber', 
'purple_blue': 'Purple Blue', 
'purple_cyan': 'Purple Cyan', 
'purple_deep_orange': 'Purple Deep Orange', 
'purple_deep_purple': 'Purple Deep Purple', 
'purple_green': 'Purple Green', 
'purple_indigo': 'Purple Indigo', 
'purple_light_blue': 'Purple Light Blue', 
'purple_light_green': 'Purple Light Green', 
'purple_lime': 'Purple Lime', 
'purple_orange': 'Purple Orange', 
'purple_pink': 'Purple Pink', 
'purple_red': 'Purple Red', 
'purple_teal': 'Purple Teal', 
'purple_yellow': 'Purple Yellow', 
'red_amber': 'Red Amber', 
'red_blue': 'Red Blue', 
'red_cyan': 'Red Cyan', 
'red_deep_orange': 'Red Deep Orange', 
'red_deep_purple': 'Red Deep Purple', 
'red_green': 'Red Green', 
'red_indigo': 'Red Indigo', 
'red_light_blue': 'Red Light Blue', 
'red_light_green': 'Red Light Green', 
'red_lime': 'Red Lime', 
'red_orange': 'Red Orange', 
'red_pink': 'Red Pink', 
'red_purple': 'Red Purple', 
'red_teal': 'Red Teal', 
'red_yellow': 'Red Yellow', 
'teal_amber': 'Teal Amber', 
'teal_blue': 'Teal Blue', 
'teal_cyan': 'Teal Cyan', 
'teal_deep_orange': 'Teal Deep Orange', 
'teal_deep_purple': 'Teal Deep Purple', 
'teal_green': 'Teal Green', 
'teal_indigo': 'Teal Indigo', 
'teal_light_blue': 'Teal Light Blue', 
'teal_light_green': 'Teal Light Green', 
'teal_lime': 'Teal Lime', 
'teal_orange': 'Teal Orange', 
'teal_pink': 'Teal Pink', 
'teal_purple': 'Teal Purple', 
'teal_red': 'Teal Red', 
'teal_yellow': 'Teal Yellow', 
'white': 'White', 
'yellow_amber': 'Yellow Amber', 
'yellow_blue': 'Yellow Blue', 
'yellow_cyan': 'Yellow Cyan', 
'yellow_deep_orange': 'Yellow Deep Orange', 
'yellow_deep_purple': 'Yellow Deep Purple', 
'yellow_green': 'Yellow Green', 
'yellow_indigo': 'Yellow Indigo', 
'yellow_light_blue': 'Yellow Light Blue', 
'yellow_light_green': 'Yellow Light Green', 
'yellow_lime': 'Yellow Lime', 
'yellow_orange': 'Yellow Orange', 
'yellow_pink': 'Yellow Pink', 
'yellow_purple': 'Yellow Purple', 
'yellow_red': 'Yellow Red', 
'yellow_teal': 'Yellow Teal', 
};
